# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yugioh_dataBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yugioh_dataBase
	pod 'Alamofire'

  target 'Yugioh_dataBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Yugioh_dataBaseUITests' do
    # Pods for testing
  end

end
